services:
  - type: web
    name: nlp-app
    env: python
    plan: free
    region: oregon
    runtime: python3.10
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
